global:
  domain: argocd.shash.com

configs:
  params:
    server.insecure: true

  cm:
    url: https://argocd.shash.com

    oidc.tls.insecure.skip.verify: "true"

    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.shash.com/realms/rke2
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email", "groups"]

  rbac:
    create: true

    policy.csv: |
      g, ArgoCDAdmins, role:admin

    scopes: "[groups]"
    policy.matchMode: "glob"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
