global:
  domain: argocd.shash.com

configs:
  params:
    server.insecure: true

  cm:
    url: https://argocd.shash.com

    oidc.config: |
      name: Keycloak
      issuer: https://keycloak.shash.com/realms/rke2
      clientID: argocd
      clientSecret: $oidc.keycloak.clientSecret
      requestedScopes: ["openid", "profile", "email"]

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    extraTls:
      - hosts:
          - argocd.shash.com
