global:
  postgresql:
    auth:
      username: bn_keycloak
      password: bn_keycloak
      database: bitnami_keycloak
  security:
    allowInsecureImages: true

image:
  repository: bitnamilegacy/keycloak

auth:
  adminUser: admin
  adminPassword: admin

postgresql:
  enabled: true
  auth:
    username: bn_keycloak
    password: bn_keycloak
    database: bitnami_keycloak
  image:
    repository: bitnamilegacy/postgresql

extraEnvVars:
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_HTTP_ENABLED
    value: "true"

  - name: VERTX_WORKER_POOL_SIZE
    value: "20"
  - name: VERTX_EVENT_LOOP_POOL_SIZE
    value: "8"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

ingress:
  enabled: true
  ingressClassName: nginx
  hostname: keycloak.shash.com
